Description of signal_generator
Home > examples > signal_generator > signal_generator.m
signal_generator
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
signal_generator
STLC_lti
This function is called by:
signal_generator
SUBFUNCTIONS
function SG= signal_generator()
SOURCE CODE
classdef signal_generator < STLC_lti
    methods
        function    SG= signal_generator()
            A =[];
            B =[];
            C =[];
            D = eye(2);
            SG = SG@STLC_lti(A,B,C,D);
        end
    end
end