Description of system_step
Home > examples > quadrotor > system_step.m
system_step
PURPOSE
SYNOPSIS
function x1 = system_step(sysd, x0, u0, w0)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
STLC_run_adversarial
STLC_run_deterministic
STLC_run_open_loop
STLC_run_open_loop_adv
SOURCE CODE
function x1 = system_step(sysd, x0, u0, w0)
        x1 = [sysd.A*x0 + sysd.B*[u0; w0]];
end